services:
  - type: web
    name: mis-gastos
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "43200"
      - key: DATABASE_URL
        fromDatabase:
          name: mis-gastos-db
          property: connectionString

databases:
  - name: mis-gastos-db
    plan: free
